// ─────────────────────────────────────────────────────────────────
// WorkflowSeedData.gs — Dữ liệu mồi (seed) cho WORKFLOW_CATALOG (H2 Giai đoạn 2)
// Nguồn: H2/Template nhập Workflow và Use case.xlsx (sheet "Ý kiến team")
// 3 Nhóm → 23 Workflow → 69 Use case. Chạy seedWorkflowCatalog() 1 lần để import.
// Sau khi seed, quản lý qua trang Cấu hình Workflow (admin) — không sửa tay file này.
// ─────────────────────────────────────────────────────────────────

// [Nhom, Workflow, UseCase]
var WORKFLOW_SEED_ROWS = [
  ['1. Workflow chung', 'Chuẩn hóa, làm sạch, đối soát & tổng hợp dữ liệu', 'AI tự động nhận diện cấu trúc và lập hồ sơ chất lượng file dữ liệu'],
  ['1. Workflow chung', 'Chuẩn hóa, làm sạch, đối soát & tổng hợp dữ liệu', 'Thư viện mapping dùng chung có version và kiểm tra thay đổi'],
  ['1. Workflow chung', 'Chuẩn hóa, làm sạch, đối soát & tổng hợp dữ liệu', 'AI đối soát đa nguồn và giải thích nguyên nhân chênh lệch'],
  ['1. Workflow chung', 'Soạn thảo, review & chuẩn hóa văn bản/email', 'AI phân loại và định tuyến văn bản/email theo loại nghiệp vụ'],
  ['1. Workflow chung', 'Soạn thảo, review & chuẩn hóa văn bản/email', 'AI so sánh phiên bản và tạo change log nghiệp vụ'],
  ['1. Workflow chung', 'Soạn thảo, review & chuẩn hóa văn bản/email', 'AI kiểm tra căn cứ, số liệu và tính nhất quán trước khi trình'],
  ['1. Workflow chung', 'Trợ lý họp & chuỗi trao đổi', 'AI tạo agenda và briefing pack trước cuộc họp'],
  ['1. Workflow chung', 'Trợ lý họp & chuỗi trao đổi', 'Decision & Commitment Tracker xuyên nhiều cuộc họp'],
  ['1. Workflow chung', 'Trợ lý họp & chuỗi trao đổi', 'AI phát hiện điểm chưa thống nhất và nội dung cần escalation'],
  ['1. Workflow chung', 'Kho tri thức, FAQ & trợ lý đào tạo', 'AI phát hiện khoảng trống kho tri thức từ câu hỏi thực tế'],
  ['1. Workflow chung', 'Kho tri thức, FAQ & trợ lý đào tạo', 'AI chuyển case thực tế thành SOP và bài học tình huống'],
  ['1. Workflow chung', 'Kho tri thức, FAQ & trợ lý đào tạo', 'AI đánh giá năng lực và gợi ý learning path cá nhân'],
  ['1. Workflow chung', 'Quản trị công việc, workload & SLA', 'AI phát hiện task trùng, phụ thuộc và xung đột deadline'],
  ['1. Workflow chung', 'Quản trị công việc, workload & SLA', 'AI dự báo capacity 4 tuần và mô phỏng phương án phân việc'],
  ['1. Workflow chung', 'Quản trị công việc, workload & SLA', 'AI tự động tạo huddle ưu tiên theo rủi ro và SLA'],
  ['1. Workflow chung', 'Dashboard, slide & truyền thông trực quan', 'AI kiểm tra tuân thủ design system và nhận diện thương hiệu'],
  ['1. Workflow chung', 'Dashboard, slide & truyền thông trực quan', 'AI sinh narrative điều hành từ KPI có kiểm chứng'],
  ['1. Workflow chung', 'Dashboard, slide & truyền thông trực quan', 'AI kiểm tra khả năng đọc và lỗi hiển thị đa thiết bị'],
  ['1. Workflow chung', 'Bảo mật dữ liệu & AI-safe workspace', 'AI phân loại dữ liệu và chặn upload sai chính sách'],
  ['1. Workflow chung', 'Bảo mật dữ liệu & AI-safe workspace', 'Sinh dữ liệu giả lập bảo toàn cấu trúc để test AI'],
  ['1. Workflow chung', 'Bảo mật dữ liệu & AI-safe workspace', 'Audit trail cho prompt, dữ liệu, model và đầu ra AI'],
  ['2. Workflow đặc thù PO', 'Nghiên cứu sản phẩm, đối thủ & định giá', 'Radar thay đổi sản phẩm đối thủ theo sự kiện'],
  ['2. Workflow đặc thù PO', 'Nghiên cứu sản phẩm, đối thủ & định giá', 'Mô phỏng phản ứng giá/phí và tác động cạnh tranh'],
  ['2. Workflow đặc thù PO', 'Nghiên cứu sản phẩm, đối thủ & định giá', 'AI nhận diện khoảng trống sản phẩm theo hành trình khách hàng'],
  ['2. Workflow đặc thù PO', 'Xây dựng/sửa đổi & phản biện hồ sơ sản phẩm', 'AI kiểm tra độ đầy đủ hồ sơ sản phẩm trước kick-off'],
  ['2. Workflow đặc thù PO', 'Xây dựng/sửa đổi & phản biện hồ sơ sản phẩm', 'AI mô phỏng tác động P&L, vận hành và rủi ro của phương án sản phẩm'],
  ['2. Workflow đặc thù PO', 'Xây dựng/sửa đổi & phản biện hồ sơ sản phẩm', 'AI tự động lắp ghép approval pack từ nguồn đã duyệt'],
  ['2. Workflow đặc thù PO', 'Pháp lý, quy định & đánh giá tác động', 'AI trích xuất nghĩa vụ và thời hạn tuân thủ từ văn bản mới'],
  ['2. Workflow đặc thù PO', 'Pháp lý, quy định & đánh giá tác động', 'AI map yêu cầu pháp lý vào sản phẩm, quy trình và control hiện hữu'],
  ['2. Workflow đặc thù PO', 'Pháp lý, quy định & đánh giá tác động', 'Compliance evidence tracker và cảnh báo tái kiểm tra'],
  ['2. Workflow đặc thù PO', 'Phát triển dự án số: BRD–US–Mockup–UAT', 'AI sinh acceptance criteria và negative cases từ User Story'],
  ['2. Workflow đặc thù PO', 'Phát triển dự án số: BRD–US–Mockup–UAT', 'AI phân loại defect và gợi ý root cause sau SIT/UAT'],
  ['2. Workflow đặc thù PO', 'Phát triển dự án số: BRD–US–Mockup–UAT', 'AI đánh giá tác động CR và chọn regression test tối thiểu'],
  ['2. Workflow đặc thù PO', 'Nghiên cứu ngành & cảnh báo thị trường', 'AI chấm độ tin cậy nguồn và chống trùng tin ngành'],
  ['2. Workflow đặc thù PO', 'Nghiên cứu ngành & cảnh báo thị trường', 'AI xây kịch bản ngành và stress test danh mục'],
  ['2. Workflow đặc thù PO', 'Nghiên cứu ngành & cảnh báo thị trường', 'AI taxonomy tín hiệu ngành và trigger hành động'],
  ['2. Workflow đặc thù PO', 'Khảo sát & Voice of Customer/ĐVKD', 'AI tạo survey thích ứng theo câu trả lời'],
  ['2. Workflow đặc thù PO', 'Khảo sát & Voice of Customer/ĐVKD', 'AI phân cụm phản hồi mở và phát hiện nhu cầu ẩn'],
  ['2. Workflow đặc thù PO', 'Khảo sát & Voice of Customer/ĐVKD', 'Trace VOC tới backlog và chính sách đã thay đổi'],
  ['2. Workflow đặc thù PO', 'Công cụ vận hành sản phẩm & pricing', 'Rule engine dùng chung cho phí, lãi, điều kiện và thẩm quyền'],
  ['2. Workflow đặc thù PO', 'Công cụ vận hành sản phẩm & pricing', 'AI phân tích ngoại lệ vận hành để đề xuất sửa sản phẩm/quy trình'],
  ['2. Workflow đặc thù PO', 'Công cụ vận hành sản phẩm & pricing', 'Control tower đối soát vận hành sản phẩm end-to-end'],
  ['2. Workflow đặc thù PO', 'Thiết kế quy trình, business case & roadmap', 'AI process mining từ log/email để dựng AS-IS thực tế'],
  ['2. Workflow đặc thù PO', 'Thiết kế quy trình, business case & roadmap', 'AI xây business case tự động hóa có sensitivity'],
  ['2. Workflow đặc thù PO', 'Thiết kế quy trình, business case & roadmap', 'AI theo dõi dependency roadmap và cảnh báo trễ dây chuyền'],
  ['3. Workflow PTKD & QLDM', 'KYC, hồ sơ pháp lý & chân dung KHDN', 'Entity Resolution – hợp nhất hồ sơ KHDN và chống trùng định danh'],
  ['3. Workflow PTKD & QLDM', 'KYC, hồ sơ pháp lý & chân dung KHDN', 'AI dựng sơ đồ UBO và phát hiện cấu trúc sở hữu bất thường'],
  ['3. Workflow PTKD & QLDM', 'KYC, hồ sơ pháp lý & chân dung KHDN', 'KYC Refresh Engine theo sự kiện và mức rủi ro'],
  ['3. Workflow PTKD & QLDM', 'Thẩm định tín dụng, dự án & phương án', 'AI trích xuất covenant và nghĩa vụ sau cấp tín dụng'],
  ['3. Workflow PTKD & QLDM', 'Thẩm định tín dụng, dự án & phương án', 'AI stress test dòng tiền và khả năng trả nợ theo scenario'],
  ['3. Workflow PTKD & QLDM', 'Thẩm định tín dụng, dự án & phương án', 'AI kiểm tra mâu thuẫn chéo giữa hồ sơ tín dụng'],
  ['3. Workflow PTKD & QLDM', 'Quản lý danh mục & cảnh báo sớm', 'Covenant Monitoring Engine và cảnh báo vi phạm dự kiến'],
  ['3. Workflow PTKD & QLDM', 'Quản lý danh mục & cảnh báo sớm', 'AI ưu tiên watchlist theo khả năng xấu đi và mức độ ảnh hưởng'],
  ['3. Workflow PTKD & QLDM', 'Quản lý danh mục & cảnh báo sớm', 'AI gợi ý next-best-remediation cho khoản có vấn đề'],
  ['3. Workflow PTKD & QLDM', 'Quản trị chiến dịch bán & pipeline', 'AI lead scoring và phân bổ data theo xác suất chuyển đổi'],
  ['3. Workflow PTKD & QLDM', 'Quản trị chiến dịch bán & pipeline', 'AI thiết kế và đánh giá A/B campaign'],
  ['3. Workflow PTKD & QLDM', 'Quản trị chiến dịch bán & pipeline', 'AI dự báo pipeline và cảnh báo deal có nguy cơ trượt'],
  ['3. Workflow PTKD & QLDM', 'Phân tích KQKD, KPI & điều hành ĐVKD', 'AI phân rã driver chênh lệch KPI theo ĐVKD'],
  ['3. Workflow PTKD & QLDM', 'Phân tích KQKD, KPI & điều hành ĐVKD', 'AI forecast gap cuối kỳ và nhu cầu can thiệp'],
  ['3. Workflow PTKD & QLDM', 'Phân tích KQKD, KPI & điều hành ĐVKD', 'AI đo hiệu quả action điều hành sau huddle'],
  ['3. Workflow PTKD & QLDM', 'Phát hiện cơ hội, upsell & hệ sinh thái', 'Next-Best-Product Engine theo nhu cầu và mức độ khai thác'],
  ['3. Workflow PTKD & QLDM', 'Phát hiện cơ hội, upsell & hệ sinh thái', 'AI phân tích phụ thuộc hệ sinh thái và cơ hội tài trợ chuỗi'],
  ['3. Workflow PTKD & QLDM', 'Phát hiện cơ hội, upsell & hệ sinh thái', 'AI phát hiện cơ hội referral liên khối/segment'],
  ['3. Workflow PTKD & QLDM', 'Trợ lý tiếp cận & làm việc với khách hàng', 'AI tạo Customer Meeting Pack 360° trước khi gặp'],
  ['3. Workflow PTKD & QLDM', 'Trợ lý tiếp cận & làm việc với khách hàng', 'AI gợi ý xử lý objection theo ngành và sản phẩm'],
  ['3. Workflow PTKD & QLDM', 'Trợ lý tiếp cận & làm việc với khách hàng', 'AI coaching chất lượng cuộc gọi/gặp khách hàng'],
  ['3. Workflow PTKD & QLDM', 'Tư vấn case & đề xuất giá/phí/tín dụng', 'Pricing Profitability Simulator cho case giá/phí'],
  ['3. Workflow PTKD & QLDM', 'Tư vấn case & đề xuất giá/phí/tín dụng', 'AI pre-check hồ sơ case và tự động routing thẩm quyền'],
  ['3. Workflow PTKD & QLDM', 'Tư vấn case & đề xuất giá/phí/tín dụng', 'AI so sánh phương án và tạo negotiation guardrails'],
];
